apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MYSQL_PASSWORD: nht1234
  MYSQL_DATABASE: phonebook
  MYSQL_USER: nihat
  MYSQL_DATABASE_HOST: mysql-service.default.svc.cluster.local